version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  redis:
    image: "redis:latest"
    container_name: redis-container
    ports:
      - "6379:6379"
    command: redis-server --requirepass pass
