CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    deadline    TIMESTAMP WITHOUT TIME ZONE,
    is_done     BOOLEAN,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT uc_task_name UNIQUE (name);

INSERT INTO task (name, description, deadline, is_done) VALUES
    ('Task 1', 'Description for Task 1', '2024-02-01', true),
    ('Task 2', 'Description for Task 2', '2024-02-15', true),
    ('Task 3', 'Description for Task 3', '2024-02-01', false),
    ('Task 4', 'Description for Task 4', '2024-02-15', true),
    ('Task 5', 'Description for Task 5', '2024-02-01', false),
    ('Task 6', 'Description for Task 6', '2024-02-15', false),
    ('Task 7', 'Description for Task 7', '2024-03-01', false);

